FROM quay.io/centos7/httpd-24-centos7

COPY ./content/index.html /var/www/html/
COPY ./content/images/* /var/www/html/images/

EXPOSE 8443

# The run script uses standard ways to run the application
CMD run-httpd